import React, { memo } from 'react';
import Svg, { G, Path, Polygon, Rect } from 'react-native-svg';
import type { Rarity } from '../../sim/types';
import { rarityRank } from '../../sim/rarity';
import { CAR_BOX_L, CAR_BOX_W } from '../lot/layout';
import { NEON, shadeColor, stripeColor } from '../theme';
import type { Archetype } from './archetypes';
import { bodyStyleOf } from './archetypes';
import { footprintFor, frameAxes, type ArtSource, type FrameAxes } from './footprint';
import { SIDE_SHAPES } from './vector/shapes';
import type { CarAngle } from './registry';

/**
 * What a trim grade looks like, drawn over whatever rendered the car.
 *
 * THIS IS AN OVERLAY, AND THAT IS THE WHOLE DESIGN. The lot draws cars from
 * baked sprites — nine archetypes by nine body colours, generated by a Blender
 * pipeline a normal checkout cannot run — so baking rarity would take that
 * matrix from 81 frames to 324 and make it unreproducible besides. Compositing
 * instead means one component covers the sprite renderer, the vector fallback
 * and every archetype nobody has drawn yet, and adds nothing to the bundle.
 *
 * It also imposes the one real constraint on the art: **trim can only add.** A
 * lift kit was the obvious treatment for a modified truck and it is not
 * available — the overlay cannot raise a body it did not draw. Fender flares
 * and a light bar say the same thing additively, and unlike ride height they
 * actually read from directly overhead, which is where sixty of these are
 * looked at.
 *
 * Two layers, because underglow belongs beneath the car and everything else
 * belongs on top of it. `CarArt` draws 'under', then the car, then 'over'.
 */

export type TrimLayer = 'under' | 'over';

export interface RarityTrimProps {
  rarity: Rarity;
  archetype: Archetype;
  angle: CarAngle;
  /** Which renderer drew the car, so the trim matches its framing. */
  source: ArtSource;
  layer: TrimLayer;
  /** On-screen width of the artboard. */
  width: number;
  /**
   * On-screen height of the artboard, from whatever drew the car.
   *
   * Passed in rather than derived from an aspect here, because the rendered
   * side frames do not share the vector elevation's proportions and a second
   * copy of that number is a second thing to forget when the camera moves.
   */
  height: number;
  /** The car's already-weathered paint, so trim ages with the car it is on. */
  paint: string;
}

/** True when this grade has anything at all to draw. */
export function hasTrim(rarity: Rarity): boolean {
  return rarityRank(rarity) > 0;
}

function RarityTrimBase({
  rarity,
  archetype,
  angle,
  source,
  layer,
  width,
  height,
  paint,
}: RarityTrimProps) {
  const rank = rarityRank(rarity);
  if (rank === 0) return null;

  const glow = rank >= 3;
  if (layer === 'under' && !glow) return null;

  if (angle === 'top') {
    return (
      <TopTrim
        archetype={archetype}
        source={source}
        layer={layer}
        width={width}
        paint={paint}
        rank={rank}
      />
    );
  }

  // The two side renderers are not two framings of one picture the way the
  // top-down pair are — one is a flat elevation and one is a three-quarter
  // shot — so they get separate overlays rather than a shared one parameterised
  // by a footprint. `axes` is present exactly when a frame was rendered.
  const axes = source === 'sprite' ? frameAxes(archetype, 'side') : null;
  if (axes) {
    return (
      <SideSpriteTrim
        archetype={archetype}
        axes={axes}
        layer={layer}
        width={width}
        height={height}
        paint={paint}
        rank={rank}
      />
    );
  }

  return <SideTrim archetype={archetype} layer={layer} width={width} paint={paint} rank={rank} />;
}

// -------------------------------------------------------------- side profile

/**
 * The feed and the sheets, where one car fills the card.
 *
 * Anchors come from `SIDE_SHAPES` rather than from numbers typed in here, so a
 * change to a body shape drags its spoiler along with it.
 *
 * The epic stripe is drawn along the flank rather than over the roof, and that
 * is not a different stripe — it is the same stripe seen from the side. A
 * hood-roof-decklid stripe is edge-on in profile and would be invisible; the
 * rocker band is what a striped car actually looks like from where this camera
 * stands. The plan view draws the over-the-top version.
 */
function SideTrim({
  archetype,
  layer,
  width,
  paint,
  rank,
}: {
  archetype: Archetype;
  layer: TrimLayer;
  width: number;
  paint: string;
  rank: number;
}) {
  const shape = SIDE_SHAPES[bodyStyleOf(archetype)] ?? SIDE_SHAPES.sedan;
  const { shoulder, sill, deck, roofY, roof, bolt } = shape.trim;
  const trim = shadeColor(paint, -0.34);
  const stripe = stripeColor(paint);

  const svg = (children: React.ReactNode) => (
    <Svg width={width} height={width * 0.44} viewBox="0 0 100 44">
      {children}
    </Svg>
  );

  if (layer === 'under') {
    // Neon spilling onto the tarmac from under the sills. Nested rather than
    // blurred: react-native-svg filter support is patchy across platforms, and
    // three stacked ellipses read as a glow at every size the game draws.
    return svg(
      <G>
        <Rect x={4} y={sill + 2.6} width={92} height={6.4} rx={3.2} fill={NEON} opacity={0.13} />
        <Rect x={11} y={sill + 2.9} width={78} height={4.6} rx={2.3} fill={NEON} opacity={0.24} />
        <Rect x={19} y={sill + 3.2} width={62} height={3} rx={1.5} fill={NEON} opacity={0.4} />
      </G>,
    );
  }

  const deckW = deck[1] - deck[0];
  const bladeX = deck[0] + deckW * 0.14;
  const bladeW = deckW * 0.74;

  return svg(
    <G>
      {bolt === 'spoiler' ? (
        <G>
          <Rect x={bladeX + bladeW * 0.16} y={shoulder - 3.8} width={1.7} height={4} fill={trim} />
          <Rect x={bladeX + bladeW * 0.68} y={shoulder - 3.8} width={1.7} height={4} fill={trim} />
          <Rect x={bladeX} y={shoulder - 5.9} width={bladeW} height={2.2} rx={1} fill={trim} />
        </G>
      ) : null}

      {bolt === 'offroad' ? (
        <G>
          {/* Arches over both wheels: a flare is a bulge on the bodywork, so it
              is a hoop struck from the wheel centre and sitting on the panel. */}
          {shape.wheels.map((cx) => {
            // Struck OUTSIDE the tyre, not through it. The overlay draws above
            // the wheels, so an arc at the tyre's own radius paints over the
            // tread and reads as a smudge rather than as bodywork.
            const r = shape.wheelR + 3;
            return (
              <Path
                key={cx}
                d={`M${cx - r},${sill} A${r},${r} 0 0 1 ${cx + r},${sill}`}
                fill="none"
                stroke={trim}
                strokeWidth={1.8}
              />
            );
          })}
          <Rect
            x={roof[0] + 2}
            y={roofY - 3.1}
            width={roof[1] - roof[0] - 4}
            height={2.4}
            rx={0.9}
            fill="#2a2f3a"
          />
          {[0.22, 0.5, 0.78].map((f) => (
            <Rect
              key={f}
              x={roof[0] + 2 + (roof[1] - roof[0] - 4) * f - 1}
              y={roofY - 2.5}
              width={2}
              height={1.2}
              rx={0.5}
              fill="#e8e2c8"
            />
          ))}
        </G>
      ) : null}

      {bolt === 'rails' ? (
        <G>
          <Rect
            x={roof[0] + 3}
            y={roofY - 2.2}
            width={roof[1] - roof[0] - 6}
            height={1.5}
            rx={0.7}
            fill={trim}
          />
          <Rect x={roof[0] + 5} y={roofY - 1} width={1.4} height={1.6} fill={trim} />
          <Rect x={roof[1] - 6.4} y={roofY - 1} width={1.4} height={1.6} fill={trim} />
        </G>
      ) : null}

      {rank >= 2 ? (
        <G>
          <Rect
            x={7}
            y={shoulder + (sill - shoulder) * 0.44}
            width={86}
            height={1.15}
            fill={stripe}
            opacity={0.8}
          />
          <Rect
            x={7}
            y={shoulder + (sill - shoulder) * 0.68}
            width={86}
            height={0.55}
            fill={stripe}
            opacity={0.8}
          />
        </G>
      ) : null}

    </G>,
  );
}

// ------------------------------------------------- three-quarter, on a sprite

/**
 * The tarmac line in the vector side artboard, which is 100 x 44 with the nose
 * at x = 0 and the tail at x = 100 — the same way round as the rendered
 * three-quarter frames. The wheels are drawn at cy 33 with a radius of 6, so
 * the tyres meet the ground here.
 */
const VECTOR_GROUND = 39;

/** Vector artboard x to car space: +1 at the nose, -1 at the tail. */
const alongLength = (x: number) => 1 - x / 50;

/** Vector artboard y to car space: 0 on the tarmac, 1 at the roof. */
const upFromGround = (y: number, roofY: number) =>
  (VECTOR_GROUND - y) / (VECTOR_GROUND - roofY);

/** Above this share of the car's height, the profile is on glass or roof. */
const GLASS_LINE = 0.75;

/**
 * The height of the boot lid itself, over the span a wing bolts to.
 *
 * The minimum rather than a sample, because everything sticking up out of a
 * rear deck — a lip, the base of a backlight — is above the lid and would only
 * ever lift the wing off it.
 */
function deckLevel(profile: number[], run: [number, number]): number {
  const n = profile.length;
  const idx = (l: number) => Math.round(((1 - l) / 2) * (n - 1));
  const from = Math.min(idx(run[0]), idx(run[1]));
  const to = Math.max(idx(run[0]), idx(run[1]));
  return Math.min(...profile.slice(from, to + 1));
}

/**
 * Where a racing stripe is allowed to run: the bonnet, the roof and the boot,
 * as spans of `l`, skipping the glass between them because a real one does.
 *
 * Found in the MEASURED roofline rather than taken from `SIDE_SHAPES`, which is
 * where the cabin sits on the stylised elevation and not where it sits on the
 * model — for a sedan the two disagree by 0.17 of half a car, enough to start
 * the roof run partway up the windscreen. The roof is the flat top, the glass
 * is the climb either side of it, and everything outside is bodywork.
 */
function stripeRuns(profile: number[]): [number, number][] {
  const n = profile.length;
  if (n < 4) return [[0.9, -0.9]];
  const lAt = (i: number) => 1 - (2 * i) / (n - 1);

  const roof = profile.map((u, i) => (u >= 0.985 ? i : -1)).filter((i) => i >= 0);
  const roofFrom = roof[0] ?? 0;
  const roofTo = roof[roof.length - 1] ?? n - 1;

  let bonnetTo = 0;
  for (let i = 0; i < roofFrom; i += 1) if (profile[i] <= GLASS_LINE) bonnetTo = i;
  let bootFrom = n - 1;
  for (let i = n - 1; i > roofTo; i -= 1) if (profile[i] <= GLASS_LINE) bootFrom = i;

  // Index 0 and the last are the bumpers, which fall away steeply; a stripe
  // that runs onto them reads as hanging off the end of the car.
  return [
    [lAt(1), lAt(bonnetTo)],
    [lAt(roofFrom), lAt(roofTo)],
    [lAt(bootFrom), lAt(n - 2)],
  ];
}

/**
 * The feed and the sheets, over a rendered three-quarter frame.
 *
 * NOTHING HERE IS POSITIONED ON THE ARTBOARD. Every point is named in the car's
 * own space — how far along its length, how far out toward the near flank, how
 * far up toward the roof — and projected through the axes the renderer measured
 * for this exact frame. That is the only way a spoiler lands on the boot rather
 * than beside it: on a three-quarter shot the car's length runs diagonally and
 * "along the tail" is not a horizontal line, so a bar drawn across the artboard
 * is a bar floating at an angle to the car it is bolted to.
 *
 * It also means this code never learns the camera. Change the angle in
 * `tools/render-cars/views.json`, re-render, and the trim follows, because the
 * numbers it reads came out of the same run as the picture underneath it.
 */
function SideSpriteTrim({
  archetype,
  axes,
  layer,
  width,
  height,
  paint,
  rank,
}: {
  archetype: Archetype;
  axes: FrameAxes;
  layer: TrimLayer;
  width: number;
  height: number;
  paint: string;
  rank: number;
}) {
  const shape = SIDE_SHAPES[bodyStyleOf(archetype)] ?? SIDE_SHAPES.sedan;
  const { sill, roofY, roof, bolt } = shape.trim;
  const trim = shadeColor(paint, -0.34);
  const stripe = stripeColor(paint);

  // WHERE things sit along the car comes from the shape table; HOW HIGH comes
  // from the measured roofline. The table is a stylised elevation — 100 x 44
  // makes a car nearly four times longer than it is tall where a real one is
  // about three — so heights read off it land low on the model, which is what
  // drew the racing stripe under the sills and through the wheel arches. What
  // it is still the authority on is a wheelbase and a cabin, which a roofline
  // cannot tell you.
  const sillU = upFromGround(sill, roofY);
  const roofL = roof.map(alongLength);

  // Percent-of-width units, so stroke widths and radii read the same at 96px in
  // the feed and at 220px on the sheet.
  const W = 100;
  const H = (100 * height) / width;

  /**
   * A point in the car's own space.
   *
   * `l` runs -1 at the tail to +1 at the nose, `w` runs -1 at the far flank to
   * +1 at the near one, `u` runs 0 at the tarmac to 1 at the roof.
   */
  const at = (l: number, w: number, u: number) => {
    const a = axes;
    return [
      (a.anchor.x + a.length.x * l + a.width.x * w + a.up.x * u) * W,
      (a.anchor.y + a.length.y * l + a.width.y * w + a.up.y * u) * H,
    ] as const;
  };
  const poly = (corners: (readonly [number, number])[]) =>
    corners.map(([x, y]) => `${x.toFixed(2)},${y.toFixed(2)}`).join(' ');

  /** The car's own roofline at a station along its length. */
  const roofline = (l: number) => {
    const p = axes.profile;
    if (!p || p.length === 0) return 1;
    // `profile` is sampled nose to tail; `l` runs +1 nose to -1 tail.
    const t = ((1 - l) / 2) * (p.length - 1);
    const i = Math.max(0, Math.min(p.length - 2, Math.floor(t)));
    return p[i] + (p[i + 1] - p[i]) * (t - i);
  };

  /**
   * A band laid ALONG the top of the car, following its roofline.
   *
   * Walks the span in steps rather than drawing one quad, because the surface
   * under it is not flat: a bonnet rises to a windscreen and a boot lid falls
   * away from a backlight, and a single quad spanning either bridges the gap in
   * mid-air. `centre` and `half` are across the car, in half-width units.
   */
  const overTheTop = (from: number, to: number, centre: number, half: number) => {
    const STEPS = 6;
    const near: (readonly [number, number])[] = [];
    const far: (readonly [number, number])[] = [];
    for (let i = 0; i <= STEPS; i += 1) {
      const l = from + ((to - from) * i) / STEPS;
      const u = roofline(l);
      near.push(at(l, centre + half, u));
      far.push(at(l, centre - half, u));
    }
    return [...near, ...far.reverse()];
  };

  // Bonnet / roof / boot, as spans of the car's own length. The last of them is
  // the boot lid, which is also where a wing bolts on.
  const runs = stripeRuns(axes.profile);
  const bladeL = runs[2][1] + 0.06;
  // The DECK, not the roofline at one station. A fastback's tail carries a lip
  // that the ray finds at 0.82 where the lid it sits on is at 0.69, and a wing
  // standing off the lip floats at roof height with daylight under it.
  const deckU = deckLevel(axes.profile, runs[2]);

  const svg = (children: React.ReactNode) => (
    <Svg width={width} height={height} viewBox={`0 0 ${W} ${H}`}>
      {children}
    </Svg>
  );

  if (layer === 'under') {
    // Neon spilling onto the tarmac. Drawn ON THE GROUND PLANE (u = 0) and
    // sheared with it, so it reads as light pooling under the car rather than
    // as a halo pasted behind it.
    //
    // Five thin layers rather than three fatter ones. react-native-svg's filter
    // support is patchy across platforms so an actual blur is out, and a
    // polygon cannot take the rounded corners the elevation's rects use — with
    // three steps the corners read as a magenta rug under the car. The
    // difference costs two polygons on the 0.1% of cars that are legendary.
    return svg(
      <G>
        {[
          [1.26, 0.06],
          [1.17, 0.08],
          [1.09, 0.11],
          [1.02, 0.15],
          [0.95, 0.22],
        ].map(([spread, opacity]) => (
          <Polygon
            key={spread}
            points={poly([
              at(spread, -spread, 0),
              at(spread, spread, 0),
              at(-spread, spread, 0),
              at(-spread, -spread, 0),
            ])}
            fill={NEON}
            opacity={opacity}
          />
        ))}
      </G>,
    );
  }

  return svg(
    <G>
      {bolt === 'spoiler' ? (
        // A wing standing off the back of the boot lid: a flat blade across the
        // car, on two uprights. Every corner is in car space, so the blade
        // shears exactly as the panel under it does instead of lying across the
        // frame at an angle of its own — and it stands off the MEASURED boot,
        // so it does not float on a body whose deck is not where the stylised
        // elevation puts it.
        <G>
          {[-0.4, 0.4].map((w) => (
            <Polygon
              key={w}
              points={poly([
                at(bladeL + 0.05, w - 0.05, deckU + 0.11),
                at(bladeL + 0.05, w + 0.05, deckU + 0.11),
                at(bladeL + 0.05, w + 0.05, deckU - 0.02),
                at(bladeL + 0.05, w - 0.05, deckU - 0.02),
              ])}
              fill={trim}
            />
          ))}
          <Polygon
            points={poly([
              at(bladeL, -0.62, deckU + 0.13),
              at(bladeL, 0.62, deckU + 0.13),
              at(bladeL + 0.11, 0.62, deckU + 0.13),
              at(bladeL + 0.11, -0.62, deckU + 0.13),
            ])}
            fill={trim}
          />
        </G>
      ) : null}

      {bolt === 'offroad' ? (
        <G>
          {/* Flares, standing proud of the bodywork over both axles. A lift is
              the obvious treatment for a modified truck and an additive overlay
              cannot draw one — it would have to raise a body it did not draw. A
              wider stance it can. */}
          {shape.wheels.map(alongLength).map((l) => (
            <Polygon
              key={l}
              points={poly([
                at(l - 0.19, 1.1, sillU + 0.16),
                at(l + 0.19, 1.1, sillU + 0.16),
                at(l + 0.24, 1.1, sillU - 0.02),
                at(l - 0.24, 1.1, sillU - 0.02),
              ])}
              fill={trim}
            />
          ))}
          {/* Light bar, on the roof just behind the windscreen header. */}
          <Polygon
            points={poly([
              at(roofL[0] - 0.14, -0.66, 1.09),
              at(roofL[0] - 0.14, 0.66, 1.09),
              at(roofL[0] - 0.02, 0.66, 1.09),
              at(roofL[0] - 0.02, -0.66, 1.09),
            ])}
            fill="#2a2f3a"
          />
          {[-0.4, 0, 0.4].map((w) => (
            <Polygon
              key={w}
              points={poly([
                at(roofL[0] - 0.12, w - 0.1, 1.08),
                at(roofL[0] - 0.12, w + 0.1, 1.08),
                at(roofL[0] - 0.04, w + 0.1, 1.08),
                at(roofL[0] - 0.04, w - 0.1, 1.08),
              ])}
              fill="#e8e2c8"
            />
          ))}
        </G>
      ) : null}

      {bolt === 'rails' ? (
        // Two rails running the length of the roof, inboard of its edges.
        <G>
          {[-0.58, 0.58].map((w) => (
            <Polygon
              key={w}
              points={poly([
                at(roofL[0] - 0.04, w - 0.06, 1.04),
                at(roofL[0] - 0.04, w + 0.06, 1.04),
                at(roofL[1] + 0.04, w + 0.06, 1.04),
                at(roofL[1] + 0.04, w - 0.06, 1.04),
              ])}
              fill={trim}
            />
          ))}
        </G>
      ) : null}

      {rank >= 2 ? (
        // The SAME stripe the plan view draws — twin runs over the bonnet, the
        // roof and the boot lid, stopping at the glass because a real one does.
        //
        // It was a rocker band along the flank, on the reasoning the vector
        // elevation used: an over-the-top stripe is edge-on in profile and
        // would be invisible. That reasoning does not survive the camera
        // moving. This shot shows the roof and the bonnet, so the stripe that
        // reads is the one over them — and a band low on the flank renders
        // through the wheel arches, which is where it was.
        //
        // Each run rides the MEASURED roofline rather than one guessed height,
        // so it sits on the bonnet, climbs to the roof and comes back down to
        // the boot on every body in the catalogue.
        <G>
          {[-1, 1].map((side) =>
            runs.map(([from, to]) => (
              <Polygon
                key={`${side}_${from}`}
                points={poly(overTheTop(from, to, side * 0.165, 0.075))}
                fill={stripe}
                opacity={0.92}
              />
            )),
          )}
        </G>
      ) : null}

    </G>,
  );
}

// ------------------------------------------------------------------ plan view

/**
 * The lot, where a car is ~34px wide and sixty of them share a screen.
 *
 * Everything is positioned off the measured footprint, so the same code lands
 * correctly on a rendered sprite and on the vector fallback despite the two
 * framing a car up to 16% differently. Nothing here is centred by assumption:
 * `cx` comes from the footprint, which is how a sprite that is off-centre in
 * its frame would still get trim on the car rather than beside it.
 */
function TopTrim({
  archetype,
  source,
  layer,
  width,
  paint,
  rank,
}: {
  archetype: Archetype;
  source: ArtSource;
  layer: TrimLayer;
  width: number;
  paint: string;
  rank: number;
}) {
  const fp = footprintFor(archetype, source);
  const bolt = SIDE_SHAPES[bodyStyleOf(archetype)]?.trim.bolt ?? 'spoiler';
  const trim = shadeColor(paint, -0.34);
  const stripe = stripeColor(paint);

  // Drawn in the vector artboard's units whichever renderer is underneath: both
  // artboards carry the same aspect to within 0.1%, so one viewBox scales to the
  // same on-screen size either way and a stripe is the same stripe.
  const W = CAR_BOX_W;
  const H = CAR_BOX_L;
  const x0 = fp.x * W;
  const x1 = fp.X * W;
  const y0 = fp.y * H;
  const y1 = fp.Y * H;
  const len = y1 - y0;
  const cx = (x0 + x1) / 2;
  const at = (f: number) => y0 + len * f;

  const svg = (children: React.ReactNode) => (
    <Svg width={width} height={width * (H / W)} viewBox={`0 0 ${W} ${H}`}>
      {children}
    </Svg>
  );

  if (layer === 'under') {
    return svg(
      <G>
        {[
          [5.5, 0.11],
          [3.2, 0.18],
          [1.5, 0.34],
        ].map(([pad, opacity]) => (
          <Rect
            key={pad}
            x={x0 - pad}
            y={y0 - pad}
            width={x1 - x0 + pad * 2}
            height={len + pad * 2}
            rx={8 + pad}
            fill={NEON}
            opacity={opacity}
          />
        ))}
      </G>,
    );
  }

  const tailW = fp.tailW * W;
  const midW = fp.midW * W;

  return svg(
    <G>
      {bolt === 'spoiler' ? (
        <G>
          <Rect
            x={cx - tailW * 0.55}
            y={at(0.9)}
            width={tailW * 1.1}
            height={len * 0.03}
            rx={1.4}
            fill={trim}
          />
          <Rect
            x={cx - tailW * 0.55}
            y={at(0.9) + len * 0.03}
            width={tailW * 1.1}
            height={len * 0.009}
            fill="#000"
            opacity={0.32}
          />
        </G>
      ) : null}

      {bolt === 'offroad' ? (
        <G>
          {/* Flares, outboard of the body at both axles. A lift is invisible
              from directly overhead; a wider stance is not. */}
          {[at(0.24), at(0.76)].map((y) =>
            [-1, 1].map((side) => (
              <Rect
                key={`${y}_${side}`}
                x={side < 0 ? x0 - W * 0.055 : x1 - W * 0.012}
                y={y - len * 0.08}
                width={W * 0.067}
                height={len * 0.16}
                rx={W * 0.026}
                fill={trim}
              />
            )),
          )}
          <Rect
            x={cx - midW * 0.37}
            y={at(0.36)}
            width={midW * 0.74}
            height={len * 0.026}
            rx={1}
            fill="#2a2f3a"
          />
          {[0, 1, 2, 3].map((i) => (
            <Rect
              key={i}
              x={cx - midW * 0.31 + i * midW * 0.2}
              y={at(0.365)}
              width={midW * 0.1}
              height={len * 0.016}
              rx={0.5}
              fill="#e8e2c8"
            />
          ))}
        </G>
      ) : null}

      {bolt === 'rails' ? (
        <G>
          {[-1, 1].map((side) => (
            <Rect
              key={side}
              x={cx + side * midW * 0.3 - midW * 0.03}
              y={at(0.33)}
              width={midW * 0.06}
              height={len * 0.48}
              rx={1}
              fill={trim}
            />
          ))}
        </G>
      ) : null}

      {rank >= 2 ? (
        <G>
          {/* Twin stripes in three runs — bonnet, roof, bootlid — because a real
              one stops at the glass rather than painting over it. */}
          {[-1, 1].map((side) =>
            [
              [0.04, 0.29],
              [0.4, 0.66],
              [0.78, 0.95],
            ].map(([a, b]) => (
              <Rect
                key={`${side}_${a}`}
                x={cx + side * midW * 0.045 - (side < 0 ? midW * 0.075 : 0)}
                y={at(a)}
                width={midW * 0.075}
                height={len * (b - a)}
                fill={stripe}
                opacity={0.92}
              />
            )),
          )}
        </G>
      ) : null}
    </G>,
  );
}

// Redrawn behind a 250ms tick on a lot that can hold sixty cars, and only ~10%
// of them have any trim at all — but the ones that do must not re-render for
// free.
export const RarityTrim = memo(RarityTrimBase);
