#!/usr/bin/env python3
"""
Pack rendered frames into the app, and generate the table the registry reads.

Two jobs the render step deliberately does not do:

- SHRINK. Cycles writes 24-bit PNGs at ~200KB each; 81 of those is 17MB, which
  is not a thing to put in a bundle that ships over GitHub Pages. These are
  flat-shaded low-poly renders with a few dozen distinct colours, so quantising
  to a palette costs nothing visible and takes ~90% off. Alpha is preserved --
  the contact shadow is a soft alpha ramp and posterising it would band.

- WIRE UP. Metro cannot resolve a computed `require`, so the sprite table has to
  be a source file with one literal require per frame. It is generated rather
  than hand-written because it is 81 lines of pure mechanism, and hand-editing it
  is how an archetype ends up pointing at another archetype's paint.

    python3 pack.py
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    sys.exit("Pillow is required: pip install Pillow")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(HERE, "build", "sprites")
DEST = os.path.join(REPO, "src", "ui", "art", "sprites")

# Ship width. The lot draws a car at ~45px at franchise scale and at most ~111px
# on a driveway, so this is comfortably above the size that matters and a little
# under the biggest. Cycles renders larger because downscaling a render is free
# and re-rendering is not.
SHIP_WIDTH = 192

# Palette size. Measured as almost irrelevant to file size next to the alpha
# channel -- 128 and 48 land within 3% of each other -- so this is set for
# quality rather than bytes.
PALETTE_COLORS = 96

# Alpha below this is rounded to fully transparent. The shadow catcher picks up
# a wash of ambient occlusion across the whole frame at alpha 1-7, invisible on
# tarmac but expensive: it denies PNG a large flat region to compress and costs
# roughly a megabyte across the set. The shadow's real soft edge sits well above
# this, so nothing that reads on screen is clipped.
ALPHA_FLOOR = 12


def pack_frame(src: str, dest: str) -> int:
    im = Image.open(src).convert("RGBA")
    height = round(SHIP_WIDTH * im.height / im.width)
    im = im.resize((SHIP_WIDTH, height), Image.LANCZOS)

    alpha = im.split()[3].point(lambda v: 0 if v < ALPHA_FLOOR else v)
    # Quantise colour only, then re-attach the 8-bit alpha, so the shadow's soft
    # edge keeps full precision instead of being posterised into bands.
    rgb = im.convert("RGB").quantize(colors=PALETTE_COLORS, method=Image.Quantize.FASTOCTREE)
    out = rgb.convert("RGBA")
    out.putalpha(alpha)
    out.save(dest, format="PNG", optimize=True)
    return os.path.getsize(dest)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--dest", default=DEST)
    args = ap.parse_args()

    with open(os.path.join(args.src, "sprites.json")) as fh:
        manifest = json.load(fh)

    if os.path.isdir(args.dest):
        shutil.rmtree(args.dest)
    os.makedirs(args.dest, exist_ok=True)

    frames = manifest["frames"]
    by_archetype: dict[str, dict[int, str]] = {}
    total_before = total_after = 0

    for frame in frames:
        src = os.path.join(args.src, frame["file"])
        dest = os.path.join(args.dest, frame["file"])
        total_before += os.path.getsize(src)
        total_after += pack_frame(src, dest)
        by_archetype.setdefault(frame["archetype"], {})[frame["index"]] = frame["file"]

    width = SHIP_WIDTH
    height = round(SHIP_WIDTH * manifest["height"] / manifest["width"])
    lines = [
        "/**",
        " * GENERATED by tools/render-sprites/pack.py. Do not edit.",
        " *",
        " * One entry per archetype per body colour, indexed to match BODY_COLORS in",
        " * src/sim/models.ts. Regenerate with:",
        " *",
        " *   cd tools/render-sprites",
        " *   python3 recolor.py && blender -b -P render.py -- --out build/sprites && python3 pack.py",
        " */",
        "import type { ImageSourcePropType } from 'react-native';",
        "",
        f"export const SPRITE_WIDTH = {width};",
        f"export const SPRITE_HEIGHT = {height};",
        "",
        "export const SPRITE_SOURCES: Record<string, readonly ImageSourcePropType[]> = {",
    ]
    for archetype in sorted(by_archetype):
        by_index = by_archetype[archetype]
        entries = ", ".join(
            f"require('./{by_index[i]}')" for i in sorted(by_index)
        )
        lines.append(f"  {archetype}: [{entries}],")
    lines.append("};")

    with open(os.path.join(args.dest, "index.ts"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    mb = lambda n: f"{n / 1024 / 1024:.2f}MB"
    print(f"packed {len(frames)} frames across {len(by_archetype)} archetypes")
    print(f"  {mb(total_before)} -> {mb(total_after)}  ({100 * total_after / total_before:.0f}%)")
    print(f"  wrote {os.path.join(args.dest, 'index.ts')}")


if __name__ == "__main__":
    main()
