/**
 * Generate the two source files the app reads from the rendered frames.
 *
 *   node tools/render-cars/pack.js
 *
 * Metro cannot resolve a computed `require`, so the sprite table has to be a
 * source file with one literal require per frame. Both files here are pure
 * mechanism and are generated rather than hand-written, because hand-editing
 * either is how an archetype ends up pointing at another archetype's paint.
 *
 * THE FOOTPRINTS ARE GENERATED TOO, and that is the point of doing this in the
 * same pipeline. They were measured by a separate tool reading the committed
 * PNGs and pasted in by hand, which works and leaves one failure mode wide
 * open: re-render the frames, forget the paste, and every spoiler on the game
 * sits a few percent off the car it is bolted to. A number written by the run
 * that produced the frame cannot go stale against it.
 */
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..', '..');
const DEST = path.join(REPO, 'src', 'ui', 'art', 'sprites');

const HEADER = (what) => `/**
 * GENERATED by tools/render-cars/pack.js. Do not edit.
 *
 * ${what}
 *
 * Regenerate with:
 *
 *   npm i -D playwright three
 *   node tools/render-cars/render.js && node tools/render-cars/pack.js
 */`;

function main() {
  const manifest = JSON.parse(fs.readFileSync(path.join(DEST, 'frames.json'), 'utf8'));
  const views = manifest.views;

  const angles = Object.keys(views).sort();
  const sourceLines = [];
  const footprintLines = [];
  const axisLines = [];

  for (const angle of angles) {
    const view = views[angle];
    const byArchetype = {};
    for (const frame of view.frames) {
      (byArchetype[frame.archetype] ??= {})[frame.index] = frame.file;
    }

    sourceLines.push(`  ${angle}: {`);
    sourceLines.push(`    width: ${view.width},`);
    sourceLines.push(`    height: ${view.height},`);
    sourceLines.push('    sources: {');
    for (const archetype of Object.keys(byArchetype).sort()) {
      const byIndex = byArchetype[archetype];
      const entries = Object.keys(byIndex)
        .map(Number)
        .sort((a, b) => a - b)
        .map((i) => `require('./${byIndex[i]}')`)
        .join(', ');
      sourceLines.push(`      ${archetype}: [${entries}],`);
    }
    sourceLines.push('    },');
    sourceLines.push('  },');

    footprintLines.push(`  ${angle}: {`);
    for (const archetype of Object.keys(view.footprints).sort()) {
      const f = view.footprints[archetype];
      footprintLines.push(
        `    ${archetype}: { x: ${f.x}, X: ${f.X}, y: ${f.y}, Y: ${f.Y}, ` +
          `hoodW: ${f.hoodW}, midW: ${f.midW}, tailW: ${f.tailW} },`,
      );
    }
    footprintLines.push('  },');

    axisLines.push(`  ${angle}: {`);
    for (const archetype of Object.keys(view.axes ?? {}).sort()) {
      const a = view.axes[archetype];
      const v = (p) => `{ x: ${p.x}, y: ${p.y} }`;
      axisLines.push(
        `    ${archetype}: { anchor: ${v(a.anchor)}, length: ${v(a.length)}, ` +
          `width: ${v(a.width)}, up: ${v(a.up)},`,
      );
      axisLines.push(`      profile: [${(a.profile ?? []).join(', ')}] },`);
    }
    axisLines.push('  },');
  }

  const index = [
    HEADER(
      'One entry per angle per archetype per body colour, indexed to match\n * BODY_COLORS in src/sim/models.ts.',
    ),
    "import type { ImageSourcePropType } from 'react-native';",
    '',
    'export interface GeneratedAngle {',
    '  /** Intrinsic frame size, so callers can scale without measuring. */',
    '  width: number;',
    '  height: number;',
    '  sources: Record<string, readonly ImageSourcePropType[]>;',
    '}',
    '',
    'export const SPRITE_ANGLES: Record<string, GeneratedAngle> = {',
    ...sourceLines,
    '};',
    '',
  ].join('\n');

  const geometry = [
    HEADER(
      'Where the car sits inside each frame and which way its own axes point,\n' +
        ' * both as fractions of the artboard. Measured at render time by the run\n' +
        ' * that produced the frame. See src/ui/art/footprint.ts for the fields.',
    ),
    "import type { FrameAxes, Footprint } from '../footprint';",
    '',
    'export const SPRITE_FOOTPRINTS: Record<string, Partial<Record<string, Footprint>>> = {',
    ...footprintLines,
    '};',
    '',
    'export const SPRITE_AXES: Record<string, Partial<Record<string, FrameAxes>>> = {',
    ...axisLines,
    '};',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(DEST, 'index.ts'), index);
  fs.writeFileSync(path.join(DEST, 'geometry.ts'), geometry);

  let bytes = 0;
  let count = 0;
  for (const angle of angles) {
    for (const frame of views[angle].frames) {
      bytes += fs.statSync(path.join(DEST, frame.file)).size;
      count += 1;
    }
    console.log(
      `  ${angle.padEnd(6)} ${views[angle].frames.length} frames  ` +
        `${views[angle].width}x${views[angle].height}`,
    );
  }
  console.log(`packed ${count} frames, ${(bytes / 1024 / 1024).toFixed(2)}MB`);
  console.log(`  wrote ${path.join(DEST, 'index.ts')}`);
  console.log(`  wrote ${path.join(DEST, 'geometry.ts')}`);
}

main();
