/**
 * GENERATED by tools/render-cars/pack.js. Do not edit.
 *
 * Where the car sits inside each frame and which way its own axes point,
 * both as fractions of the artboard. Measured at render time by the run
 * that produced the frame. See src/ui/art/footprint.ts for the fields.
 *
 * Regenerate with:
 *
 *   npm i -D playwright three
 *   node tools/render-cars/render.js && node tools/render-cars/pack.js
 */
import type { FrameAxes, Footprint } from '../footprint';

export const SPRITE_FOOTPRINTS: Record<string, Partial<Record<string, Footprint>>> = {
  side: {
    coupePremium: { x: 0.184, X: 0.816, y: 0.273, Y: 0.852, hoodW: 0.462, midW: 0.594, tailW: 0.354 },
    hatchEconomy: { x: 0.142, X: 0.858, y: 0.227, Y: 0.864, hoodW: 0.462, midW: 0.681, tailW: 0.424 },
    sedanEconomy: { x: 0.16, X: 0.84, y: 0.165, Y: 0.858, hoodW: 0.417, midW: 0.667, tailW: 0.413 },
    sedanPremium: { x: 0.146, X: 0.854, y: 0.216, Y: 0.858, hoodW: 0.514, midW: 0.681, tailW: 0.413 },
    suvEconomy: { x: 0.146, X: 0.861, y: 0.153, Y: 0.858, hoodW: 0.486, midW: 0.681, tailW: 0.424 },
    suvPremium: { x: 0.094, X: 0.917, y: 0.057, Y: 0.875, hoodW: 0.559, midW: 0.785, tailW: 0.486 },
    truckEconomy: { x: 0.115, X: 0.885, y: 0.205, Y: 0.875, hoodW: 0.58, midW: 0.719, tailW: 0.41 },
    truckPremium: { x: 0.056, X: 0.944, y: 0.119, Y: 0.892, hoodW: 0.667, midW: 0.823, tailW: 0.462 },
    vanEconomy: { x: 0.125, X: 0.875, y: 0.085, Y: 0.869, hoodW: 0.563, midW: 0.74, tailW: 0.469 },
  },
  top: {
    coupePremium: { x: 0.156, X: 0.844, y: 0.159, Y: 0.814, hoodW: 0.688, midW: 0.688, tailW: 0.688 },
    hatchEconomy: { x: 0.141, X: 0.859, y: 0.106, Y: 0.864, hoodW: 0.719, midW: 0.719, tailW: 0.719 },
    sedanEconomy: { x: 0.073, X: 0.927, y: 0.128, Y: 0.836, hoodW: 0.74, midW: 0.74, tailW: 0.74 },
    sedanPremium: { x: 0.115, X: 0.885, y: 0.118, Y: 0.851, hoodW: 0.771, midW: 0.771, tailW: 0.771 },
    suvEconomy: { x: 0.094, X: 0.901, y: 0.093, Y: 0.856, hoodW: 0.698, midW: 0.698, tailW: 0.698 },
    suvPremium: { x: 0.036, X: 0.964, y: 0.033, Y: 0.909, hoodW: 0.802, midW: 0.802, tailW: 0.802 },
    truckEconomy: { x: 0.073, X: 0.927, y: 0.068, Y: 0.892, hoodW: 0.74, midW: 0.74, tailW: 0.74 },
    truckPremium: { x: 0.005, X: 0.995, y: 0, Y: 0.95, hoodW: 0.854, midW: 0.854, tailW: 0.854 },
    vanEconomy: { x: 0.052, X: 0.948, y: 0.078, Y: 0.879, hoodW: 0.771, midW: 0.771, tailW: 0.771 },
  },
};

export const SPRITE_AXES: Record<string, Partial<Record<string, FrameAxes>>> = {
  side: {
    coupePremium: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.2753, y: 0.0944 }, width: { x: 0.0625, y: 0.1081 }, up: { x: 0, y: -0.3769 } },
    hatchEconomy: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.3176, y: 0.109 }, width: { x: 0.0645, y: 0.1116 }, up: { x: 0, y: -0.3891 } },
    sedanEconomy: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.296, y: 0.1015 }, width: { x: 0.0775, y: 0.1342 }, up: { x: 0, y: -0.479 } },
    sedanPremium: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.3079, y: 0.1056 }, width: { x: 0.0699, y: 0.1209 }, up: { x: 0, y: -0.4215 } },
    suvEconomy: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.311, y: 0.1067 }, width: { x: 0.0729, y: 0.1261 }, up: { x: 0, y: -0.4502 } },
    suvPremium: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.3573, y: 0.1226 }, width: { x: 0.0837, y: 0.1449 }, up: { x: 0, y: -0.5173 } },
    truckEconomy: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.3424, y: 0.1175 }, width: { x: 0.0775, y: 0.1342 }, up: { x: 0, y: -0.479 } },
    truckPremium: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.3938, y: 0.1351 }, width: { x: 0.0892, y: 0.1543 }, up: { x: 0, y: -0.5508 } },
    vanEconomy: { anchor: { x: 0.5, y: 0.7586 }, length: { x: -0.332, y: 0.1139 }, width: { x: 0.0806, y: 0.1395 }, up: { x: 0, y: -0.5173 } },
  },
  top: {
    coupePremium: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3232 }, width: { x: 0.3481, y: 0 }, up: { x: 0, y: -0.0593 } },
    hatchEconomy: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3729 }, width: { x: 0.3594, y: 0 }, up: { x: 0, y: -0.0612 } },
    sedanEconomy: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3475 }, width: { x: 0.4319, y: 0 }, up: { x: 0, y: -0.0753 } },
    sedanPremium: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3614 }, width: { x: 0.3893, y: 0 }, up: { x: 0, y: -0.0663 } },
    suvEconomy: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3651 }, width: { x: 0.406, y: 0 }, up: { x: 0, y: -0.0708 } },
    suvPremium: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.4195 }, width: { x: 0.4665, y: 0 }, up: { x: 0, y: -0.0813 } },
    truckEconomy: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.4021 }, width: { x: 0.4319, y: 0 }, up: { x: 0, y: -0.0753 } },
    truckPremium: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.4624 }, width: { x: 0.4967, y: 0 }, up: { x: 0, y: -0.0866 } },
    vanEconomy: { anchor: { x: 0.5, y: 0.5 }, length: { x: 0, y: 0.3898 }, width: { x: 0.4492, y: 0 }, up: { x: 0, y: -0.0813 } },
  },
};
