/**
 * GENERATED by tools/render-cars/pack.js. Do not edit.
 *
 * One entry per angle per archetype per body colour, indexed to match
 * BODY_COLORS in src/sim/models.ts.
 *
 * Regenerate with:
 *
 *   npm i -D playwright three
 *   node tools/render-cars/render.js && node tools/render-cars/pack.js
 */
import type { ImageSourcePropType } from 'react-native';

export interface GeneratedAngle {
  /** Intrinsic frame size, so callers can scale without measuring. */
  width: number;
  height: number;
  sources: Record<string, readonly ImageSourcePropType[]>;
}

export const SPRITE_ANGLES: Record<string, GeneratedAngle> = {
  side: {
    width: 288,
    height: 176,
    sources: {
      coupePremium: [require('./coupePremium-side_00.png'), require('./coupePremium-side_01.png'), require('./coupePremium-side_02.png'), require('./coupePremium-side_03.png'), require('./coupePremium-side_04.png'), require('./coupePremium-side_05.png'), require('./coupePremium-side_06.png'), require('./coupePremium-side_07.png'), require('./coupePremium-side_08.png')],
      hatchEconomy: [require('./hatchEconomy-side_00.png'), require('./hatchEconomy-side_01.png'), require('./hatchEconomy-side_02.png'), require('./hatchEconomy-side_03.png'), require('./hatchEconomy-side_04.png'), require('./hatchEconomy-side_05.png'), require('./hatchEconomy-side_06.png'), require('./hatchEconomy-side_07.png'), require('./hatchEconomy-side_08.png')],
      sedanEconomy: [require('./sedanEconomy-side_00.png'), require('./sedanEconomy-side_01.png'), require('./sedanEconomy-side_02.png'), require('./sedanEconomy-side_03.png'), require('./sedanEconomy-side_04.png'), require('./sedanEconomy-side_05.png'), require('./sedanEconomy-side_06.png'), require('./sedanEconomy-side_07.png'), require('./sedanEconomy-side_08.png')],
      sedanPremium: [require('./sedanPremium-side_00.png'), require('./sedanPremium-side_01.png'), require('./sedanPremium-side_02.png'), require('./sedanPremium-side_03.png'), require('./sedanPremium-side_04.png'), require('./sedanPremium-side_05.png'), require('./sedanPremium-side_06.png'), require('./sedanPremium-side_07.png'), require('./sedanPremium-side_08.png')],
      suvEconomy: [require('./suvEconomy-side_00.png'), require('./suvEconomy-side_01.png'), require('./suvEconomy-side_02.png'), require('./suvEconomy-side_03.png'), require('./suvEconomy-side_04.png'), require('./suvEconomy-side_05.png'), require('./suvEconomy-side_06.png'), require('./suvEconomy-side_07.png'), require('./suvEconomy-side_08.png')],
      suvPremium: [require('./suvPremium-side_00.png'), require('./suvPremium-side_01.png'), require('./suvPremium-side_02.png'), require('./suvPremium-side_03.png'), require('./suvPremium-side_04.png'), require('./suvPremium-side_05.png'), require('./suvPremium-side_06.png'), require('./suvPremium-side_07.png'), require('./suvPremium-side_08.png')],
      truckEconomy: [require('./truckEconomy-side_00.png'), require('./truckEconomy-side_01.png'), require('./truckEconomy-side_02.png'), require('./truckEconomy-side_03.png'), require('./truckEconomy-side_04.png'), require('./truckEconomy-side_05.png'), require('./truckEconomy-side_06.png'), require('./truckEconomy-side_07.png'), require('./truckEconomy-side_08.png')],
      truckPremium: [require('./truckPremium-side_00.png'), require('./truckPremium-side_01.png'), require('./truckPremium-side_02.png'), require('./truckPremium-side_03.png'), require('./truckPremium-side_04.png'), require('./truckPremium-side_05.png'), require('./truckPremium-side_06.png'), require('./truckPremium-side_07.png'), require('./truckPremium-side_08.png')],
      vanEconomy: [require('./vanEconomy-side_00.png'), require('./vanEconomy-side_01.png'), require('./vanEconomy-side_02.png'), require('./vanEconomy-side_03.png'), require('./vanEconomy-side_04.png'), require('./vanEconomy-side_05.png'), require('./vanEconomy-side_06.png'), require('./vanEconomy-side_07.png'), require('./vanEconomy-side_08.png')],
    },
  },
  top: {
    width: 192,
    height: 397,
    sources: {
      coupePremium: [require('./coupePremium_00.png'), require('./coupePremium_01.png'), require('./coupePremium_02.png'), require('./coupePremium_03.png'), require('./coupePremium_04.png'), require('./coupePremium_05.png'), require('./coupePremium_06.png'), require('./coupePremium_07.png'), require('./coupePremium_08.png')],
      hatchEconomy: [require('./hatchEconomy_00.png'), require('./hatchEconomy_01.png'), require('./hatchEconomy_02.png'), require('./hatchEconomy_03.png'), require('./hatchEconomy_04.png'), require('./hatchEconomy_05.png'), require('./hatchEconomy_06.png'), require('./hatchEconomy_07.png'), require('./hatchEconomy_08.png')],
      sedanEconomy: [require('./sedanEconomy_00.png'), require('./sedanEconomy_01.png'), require('./sedanEconomy_02.png'), require('./sedanEconomy_03.png'), require('./sedanEconomy_04.png'), require('./sedanEconomy_05.png'), require('./sedanEconomy_06.png'), require('./sedanEconomy_07.png'), require('./sedanEconomy_08.png')],
      sedanPremium: [require('./sedanPremium_00.png'), require('./sedanPremium_01.png'), require('./sedanPremium_02.png'), require('./sedanPremium_03.png'), require('./sedanPremium_04.png'), require('./sedanPremium_05.png'), require('./sedanPremium_06.png'), require('./sedanPremium_07.png'), require('./sedanPremium_08.png')],
      suvEconomy: [require('./suvEconomy_00.png'), require('./suvEconomy_01.png'), require('./suvEconomy_02.png'), require('./suvEconomy_03.png'), require('./suvEconomy_04.png'), require('./suvEconomy_05.png'), require('./suvEconomy_06.png'), require('./suvEconomy_07.png'), require('./suvEconomy_08.png')],
      suvPremium: [require('./suvPremium_00.png'), require('./suvPremium_01.png'), require('./suvPremium_02.png'), require('./suvPremium_03.png'), require('./suvPremium_04.png'), require('./suvPremium_05.png'), require('./suvPremium_06.png'), require('./suvPremium_07.png'), require('./suvPremium_08.png')],
      truckEconomy: [require('./truckEconomy_00.png'), require('./truckEconomy_01.png'), require('./truckEconomy_02.png'), require('./truckEconomy_03.png'), require('./truckEconomy_04.png'), require('./truckEconomy_05.png'), require('./truckEconomy_06.png'), require('./truckEconomy_07.png'), require('./truckEconomy_08.png')],
      truckPremium: [require('./truckPremium_00.png'), require('./truckPremium_01.png'), require('./truckPremium_02.png'), require('./truckPremium_03.png'), require('./truckPremium_04.png'), require('./truckPremium_05.png'), require('./truckPremium_06.png'), require('./truckPremium_07.png'), require('./truckPremium_08.png')],
      vanEconomy: [require('./vanEconomy_00.png'), require('./vanEconomy_01.png'), require('./vanEconomy_02.png'), require('./vanEconomy_03.png'), require('./vanEconomy_04.png'), require('./vanEconomy_05.png'), require('./vanEconomy_06.png'), require('./vanEconomy_07.png'), require('./vanEconomy_08.png')],
    },
  },
};
